name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          args: -pdf -file-line-error -interaction=nonstopmode -f
        continue-on-error: true
      - run: |
          curl -F "payload_json={\"username\": \"TeXy\", \"content\": \"New LaTeX document at \`$GITHUB_REPOSITORY:$GITHUB_REF_NAME\`\"}" -F "file1=@main.pdf" ${{ secrets.DISCORD_WEBHOOK_URL }}
